version: '3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: senyaginserg/foodgram-backend:latest
    restart: always
    volumes:
      - backend_static:/app/backend_static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - backend_static:/app/backend_static/
      - media_value:/app/media/
    depends_on:
      - backend

  frontend:
    image: senyaginserg/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - nginx

volumes:
  db:
  backend_static:
  media_value:
