# Generated by Django 3.2.15 on 2023-08-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountingredients',
            options={'verbose_name': 'Ингридиент в рецепте', 'verbose_name_plural': 'Ингридиентов в рецепте'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'Список покупок', 'verbose_name_plural': 'Список покупок'},
        ),
    ]
